# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/bryanc/devel/repos-git/libviper

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/bryanc/devel/repos-git/libviper

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bryanc/devel/repos-git/libviper/CMakeFiles /home/bryanc/devel/repos-git/libviper//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bryanc/devel/repos-git/libviper/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named vdk.o

# Build rule for target.
vdk.o: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vdk.o
.PHONY : vdk.o

# fast build rule for target.
vdk.o/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/build
.PHONY : vdk.o/fast

#=============================================================================
# Target rules for targets named vdk-static

# Build rule for target.
vdk-static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vdk-static
.PHONY : vdk-static

# fast build rule for target.
vdk-static/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk-static.dir/build.make CMakeFiles/vdk-static.dir/build
.PHONY : vdk-static/fast

#=============================================================================
# Target rules for targets named vdk-shared

# Build rule for target.
vdk-shared: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vdk-shared
.PHONY : vdk-shared

# fast build rule for target.
vdk-shared/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk-shared.dir/build.make CMakeFiles/vdk-shared.dir/build
.PHONY : vdk-shared/fast

#=============================================================================
# Target rules for targets named vk_demo

# Build rule for target.
vk_demo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vk_demo
.PHONY : vk_demo

# fast build rule for target.
vk_demo/fast:
	$(MAKE) $(MAKESILENT) -f demo/CMakeFiles/vk_demo.dir/build.make demo/CMakeFiles/vk_demo.dir/build
.PHONY : vk_demo/fast

vdk/vdk_color.o: vdk/vdk_color.c.o
.PHONY : vdk/vdk_color.o

# target to build an object file
vdk/vdk_color.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vdk/vdk_color.c.o
.PHONY : vdk/vdk_color.c.o

vdk/vdk_color.i: vdk/vdk_color.c.i
.PHONY : vdk/vdk_color.i

# target to preprocess a source file
vdk/vdk_color.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vdk/vdk_color.c.i
.PHONY : vdk/vdk_color.c.i

vdk/vdk_color.s: vdk/vdk_color.c.s
.PHONY : vdk/vdk_color.s

# target to generate assembly for a file
vdk/vdk_color.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vdk/vdk_color.c.s
.PHONY : vdk/vdk_color.c.s

vdk/vk_activity.o: vdk/vk_activity.c.o
.PHONY : vdk/vk_activity.o

# target to build an object file
vdk/vk_activity.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vdk/vk_activity.c.o
.PHONY : vdk/vk_activity.c.o

vdk/vk_activity.i: vdk/vk_activity.c.i
.PHONY : vdk/vk_activity.i

# target to preprocess a source file
vdk/vk_activity.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vdk/vk_activity.c.i
.PHONY : vdk/vk_activity.c.i

vdk/vk_activity.s: vdk/vk_activity.c.s
.PHONY : vdk/vk_activity.s

# target to generate assembly for a file
vdk/vk_activity.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vdk/vk_activity.c.s
.PHONY : vdk/vk_activity.c.s

vdk/vk_box.o: vdk/vk_box.c.o
.PHONY : vdk/vk_box.o

# target to build an object file
vdk/vk_box.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vdk/vk_box.c.o
.PHONY : vdk/vk_box.c.o

vdk/vk_box.i: vdk/vk_box.c.i
.PHONY : vdk/vk_box.i

# target to preprocess a source file
vdk/vk_box.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vdk/vk_box.c.i
.PHONY : vdk/vk_box.c.i

vdk/vk_box.s: vdk/vk_box.c.s
.PHONY : vdk/vk_box.s

# target to generate assembly for a file
vdk/vk_box.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vdk/vk_box.c.s
.PHONY : vdk/vk_box.c.s

vdk/vk_button.o: vdk/vk_button.c.o
.PHONY : vdk/vk_button.o

# target to build an object file
vdk/vk_button.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vdk/vk_button.c.o
.PHONY : vdk/vk_button.c.o

vdk/vk_button.i: vdk/vk_button.c.i
.PHONY : vdk/vk_button.i

# target to preprocess a source file
vdk/vk_button.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vdk/vk_button.c.i
.PHONY : vdk/vk_button.c.i

vdk/vk_button.s: vdk/vk_button.c.s
.PHONY : vdk/vk_button.s

# target to generate assembly for a file
vdk/vk_button.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vdk/vk_button.c.s
.PHONY : vdk/vk_button.c.s

vdk/vk_calendar.o: vdk/vk_calendar.c.o
.PHONY : vdk/vk_calendar.o

# target to build an object file
vdk/vk_calendar.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vdk/vk_calendar.c.o
.PHONY : vdk/vk_calendar.c.o

vdk/vk_calendar.i: vdk/vk_calendar.c.i
.PHONY : vdk/vk_calendar.i

# target to preprocess a source file
vdk/vk_calendar.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vdk/vk_calendar.c.i
.PHONY : vdk/vk_calendar.c.i

vdk/vk_calendar.s: vdk/vk_calendar.c.s
.PHONY : vdk/vk_calendar.s

# target to generate assembly for a file
vdk/vk_calendar.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vdk/vk_calendar.c.s
.PHONY : vdk/vk_calendar.c.s

vdk/vk_container.o: vdk/vk_container.c.o
.PHONY : vdk/vk_container.o

# target to build an object file
vdk/vk_container.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vdk/vk_container.c.o
.PHONY : vdk/vk_container.c.o

vdk/vk_container.i: vdk/vk_container.c.i
.PHONY : vdk/vk_container.i

# target to preprocess a source file
vdk/vk_container.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vdk/vk_container.c.i
.PHONY : vdk/vk_container.c.i

vdk/vk_container.s: vdk/vk_container.c.s
.PHONY : vdk/vk_container.s

# target to generate assembly for a file
vdk/vk_container.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vdk/vk_container.c.s
.PHONY : vdk/vk_container.c.s

vdk/vk_deck.o: vdk/vk_deck.c.o
.PHONY : vdk/vk_deck.o

# target to build an object file
vdk/vk_deck.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vdk/vk_deck.c.o
.PHONY : vdk/vk_deck.c.o

vdk/vk_deck.i: vdk/vk_deck.c.i
.PHONY : vdk/vk_deck.i

# target to preprocess a source file
vdk/vk_deck.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vdk/vk_deck.c.i
.PHONY : vdk/vk_deck.c.i

vdk/vk_deck.s: vdk/vk_deck.c.s
.PHONY : vdk/vk_deck.s

# target to generate assembly for a file
vdk/vk_deck.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vdk/vk_deck.c.s
.PHONY : vdk/vk_deck.c.s

vdk/vk_dropdown.o: vdk/vk_dropdown.c.o
.PHONY : vdk/vk_dropdown.o

# target to build an object file
vdk/vk_dropdown.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vdk/vk_dropdown.c.o
.PHONY : vdk/vk_dropdown.c.o

vdk/vk_dropdown.i: vdk/vk_dropdown.c.i
.PHONY : vdk/vk_dropdown.i

# target to preprocess a source file
vdk/vk_dropdown.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vdk/vk_dropdown.c.i
.PHONY : vdk/vk_dropdown.c.i

vdk/vk_dropdown.s: vdk/vk_dropdown.c.s
.PHONY : vdk/vk_dropdown.s

# target to generate assembly for a file
vdk/vk_dropdown.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vdk/vk_dropdown.c.s
.PHONY : vdk/vk_dropdown.c.s

vdk/vk_filedialog.o: vdk/vk_filedialog.c.o
.PHONY : vdk/vk_filedialog.o

# target to build an object file
vdk/vk_filedialog.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vdk/vk_filedialog.c.o
.PHONY : vdk/vk_filedialog.c.o

vdk/vk_filedialog.i: vdk/vk_filedialog.c.i
.PHONY : vdk/vk_filedialog.i

# target to preprocess a source file
vdk/vk_filedialog.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vdk/vk_filedialog.c.i
.PHONY : vdk/vk_filedialog.c.i

vdk/vk_filedialog.s: vdk/vk_filedialog.c.s
.PHONY : vdk/vk_filedialog.s

# target to generate assembly for a file
vdk/vk_filedialog.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vdk/vk_filedialog.c.s
.PHONY : vdk/vk_filedialog.c.s

vdk/vk_filler.o: vdk/vk_filler.c.o
.PHONY : vdk/vk_filler.o

# target to build an object file
vdk/vk_filler.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vdk/vk_filler.c.o
.PHONY : vdk/vk_filler.c.o

vdk/vk_filler.i: vdk/vk_filler.c.i
.PHONY : vdk/vk_filler.i

# target to preprocess a source file
vdk/vk_filler.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vdk/vk_filler.c.i
.PHONY : vdk/vk_filler.c.i

vdk/vk_filler.s: vdk/vk_filler.c.s
.PHONY : vdk/vk_filler.s

# target to generate assembly for a file
vdk/vk_filler.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vdk/vk_filler.c.s
.PHONY : vdk/vk_filler.c.s

vdk/vk_frame.o: vdk/vk_frame.c.o
.PHONY : vdk/vk_frame.o

# target to build an object file
vdk/vk_frame.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vdk/vk_frame.c.o
.PHONY : vdk/vk_frame.c.o

vdk/vk_frame.i: vdk/vk_frame.c.i
.PHONY : vdk/vk_frame.i

# target to preprocess a source file
vdk/vk_frame.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vdk/vk_frame.c.i
.PHONY : vdk/vk_frame.c.i

vdk/vk_frame.s: vdk/vk_frame.c.s
.PHONY : vdk/vk_frame.s

# target to generate assembly for a file
vdk/vk_frame.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vdk/vk_frame.c.s
.PHONY : vdk/vk_frame.c.s

vdk/vk_input.o: vdk/vk_input.c.o
.PHONY : vdk/vk_input.o

# target to build an object file
vdk/vk_input.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vdk/vk_input.c.o
.PHONY : vdk/vk_input.c.o

vdk/vk_input.i: vdk/vk_input.c.i
.PHONY : vdk/vk_input.i

# target to preprocess a source file
vdk/vk_input.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vdk/vk_input.c.i
.PHONY : vdk/vk_input.c.i

vdk/vk_input.s: vdk/vk_input.c.s
.PHONY : vdk/vk_input.s

# target to generate assembly for a file
vdk/vk_input.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vdk/vk_input.c.s
.PHONY : vdk/vk_input.c.s

vdk/vk_label.o: vdk/vk_label.c.o
.PHONY : vdk/vk_label.o

# target to build an object file
vdk/vk_label.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vdk/vk_label.c.o
.PHONY : vdk/vk_label.c.o

vdk/vk_label.i: vdk/vk_label.c.i
.PHONY : vdk/vk_label.i

# target to preprocess a source file
vdk/vk_label.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vdk/vk_label.c.i
.PHONY : vdk/vk_label.c.i

vdk/vk_label.s: vdk/vk_label.c.s
.PHONY : vdk/vk_label.s

# target to generate assembly for a file
vdk/vk_label.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vdk/vk_label.c.s
.PHONY : vdk/vk_label.c.s

vdk/vk_listbox.o: vdk/vk_listbox.c.o
.PHONY : vdk/vk_listbox.o

# target to build an object file
vdk/vk_listbox.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vdk/vk_listbox.c.o
.PHONY : vdk/vk_listbox.c.o

vdk/vk_listbox.i: vdk/vk_listbox.c.i
.PHONY : vdk/vk_listbox.i

# target to preprocess a source file
vdk/vk_listbox.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vdk/vk_listbox.c.i
.PHONY : vdk/vk_listbox.c.i

vdk/vk_listbox.s: vdk/vk_listbox.c.s
.PHONY : vdk/vk_listbox.s

# target to generate assembly for a file
vdk/vk_listbox.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vdk/vk_listbox.c.s
.PHONY : vdk/vk_listbox.c.s

vdk/vk_marquee.o: vdk/vk_marquee.c.o
.PHONY : vdk/vk_marquee.o

# target to build an object file
vdk/vk_marquee.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vdk/vk_marquee.c.o
.PHONY : vdk/vk_marquee.c.o

vdk/vk_marquee.i: vdk/vk_marquee.c.i
.PHONY : vdk/vk_marquee.i

# target to preprocess a source file
vdk/vk_marquee.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vdk/vk_marquee.c.i
.PHONY : vdk/vk_marquee.c.i

vdk/vk_marquee.s: vdk/vk_marquee.c.s
.PHONY : vdk/vk_marquee.s

# target to generate assembly for a file
vdk/vk_marquee.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vdk/vk_marquee.c.s
.PHONY : vdk/vk_marquee.c.s

vdk/vk_menubar.o: vdk/vk_menubar.c.o
.PHONY : vdk/vk_menubar.o

# target to build an object file
vdk/vk_menubar.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vdk/vk_menubar.c.o
.PHONY : vdk/vk_menubar.c.o

vdk/vk_menubar.i: vdk/vk_menubar.c.i
.PHONY : vdk/vk_menubar.i

# target to preprocess a source file
vdk/vk_menubar.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vdk/vk_menubar.c.i
.PHONY : vdk/vk_menubar.c.i

vdk/vk_menubar.s: vdk/vk_menubar.c.s
.PHONY : vdk/vk_menubar.s

# target to generate assembly for a file
vdk/vk_menubar.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vdk/vk_menubar.c.s
.PHONY : vdk/vk_menubar.c.s

vdk/vk_object.o: vdk/vk_object.c.o
.PHONY : vdk/vk_object.o

# target to build an object file
vdk/vk_object.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vdk/vk_object.c.o
.PHONY : vdk/vk_object.c.o

vdk/vk_object.i: vdk/vk_object.c.i
.PHONY : vdk/vk_object.i

# target to preprocess a source file
vdk/vk_object.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vdk/vk_object.c.i
.PHONY : vdk/vk_object.c.i

vdk/vk_object.s: vdk/vk_object.c.s
.PHONY : vdk/vk_object.s

# target to generate assembly for a file
vdk/vk_object.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vdk/vk_object.c.s
.PHONY : vdk/vk_object.c.s

vdk/vk_popup.o: vdk/vk_popup.c.o
.PHONY : vdk/vk_popup.o

# target to build an object file
vdk/vk_popup.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vdk/vk_popup.c.o
.PHONY : vdk/vk_popup.c.o

vdk/vk_popup.i: vdk/vk_popup.c.i
.PHONY : vdk/vk_popup.i

# target to preprocess a source file
vdk/vk_popup.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vdk/vk_popup.c.i
.PHONY : vdk/vk_popup.c.i

vdk/vk_popup.s: vdk/vk_popup.c.s
.PHONY : vdk/vk_popup.s

# target to generate assembly for a file
vdk/vk_popup.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vdk/vk_popup.c.s
.PHONY : vdk/vk_popup.c.s

vdk/vk_screen.o: vdk/vk_screen.c.o
.PHONY : vdk/vk_screen.o

# target to build an object file
vdk/vk_screen.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vdk/vk_screen.c.o
.PHONY : vdk/vk_screen.c.o

vdk/vk_screen.i: vdk/vk_screen.c.i
.PHONY : vdk/vk_screen.i

# target to preprocess a source file
vdk/vk_screen.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vdk/vk_screen.c.i
.PHONY : vdk/vk_screen.c.i

vdk/vk_screen.s: vdk/vk_screen.c.s
.PHONY : vdk/vk_screen.s

# target to generate assembly for a file
vdk/vk_screen.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vdk/vk_screen.c.s
.PHONY : vdk/vk_screen.c.s

vdk/vk_scroller.o: vdk/vk_scroller.c.o
.PHONY : vdk/vk_scroller.o

# target to build an object file
vdk/vk_scroller.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vdk/vk_scroller.c.o
.PHONY : vdk/vk_scroller.c.o

vdk/vk_scroller.i: vdk/vk_scroller.c.i
.PHONY : vdk/vk_scroller.i

# target to preprocess a source file
vdk/vk_scroller.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vdk/vk_scroller.c.i
.PHONY : vdk/vk_scroller.c.i

vdk/vk_scroller.s: vdk/vk_scroller.c.s
.PHONY : vdk/vk_scroller.s

# target to generate assembly for a file
vdk/vk_scroller.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vdk/vk_scroller.c.s
.PHONY : vdk/vk_scroller.c.s

vdk/vk_selectbox.o: vdk/vk_selectbox.c.o
.PHONY : vdk/vk_selectbox.o

# target to build an object file
vdk/vk_selectbox.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vdk/vk_selectbox.c.o
.PHONY : vdk/vk_selectbox.c.o

vdk/vk_selectbox.i: vdk/vk_selectbox.c.i
.PHONY : vdk/vk_selectbox.i

# target to preprocess a source file
vdk/vk_selectbox.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vdk/vk_selectbox.c.i
.PHONY : vdk/vk_selectbox.c.i

vdk/vk_selectbox.s: vdk/vk_selectbox.c.s
.PHONY : vdk/vk_selectbox.s

# target to generate assembly for a file
vdk/vk_selectbox.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vdk/vk_selectbox.c.s
.PHONY : vdk/vk_selectbox.c.s

vdk/vk_textbox.o: vdk/vk_textbox.c.o
.PHONY : vdk/vk_textbox.o

# target to build an object file
vdk/vk_textbox.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vdk/vk_textbox.c.o
.PHONY : vdk/vk_textbox.c.o

vdk/vk_textbox.i: vdk/vk_textbox.c.i
.PHONY : vdk/vk_textbox.i

# target to preprocess a source file
vdk/vk_textbox.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vdk/vk_textbox.c.i
.PHONY : vdk/vk_textbox.c.i

vdk/vk_textbox.s: vdk/vk_textbox.c.s
.PHONY : vdk/vk_textbox.s

# target to generate assembly for a file
vdk/vk_textbox.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vdk/vk_textbox.c.s
.PHONY : vdk/vk_textbox.c.s

vdk/vk_widget.o: vdk/vk_widget.c.o
.PHONY : vdk/vk_widget.o

# target to build an object file
vdk/vk_widget.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vdk/vk_widget.c.o
.PHONY : vdk/vk_widget.c.o

vdk/vk_widget.i: vdk/vk_widget.c.i
.PHONY : vdk/vk_widget.i

# target to preprocess a source file
vdk/vk_widget.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vdk/vk_widget.c.i
.PHONY : vdk/vk_widget.c.i

vdk/vk_widget.s: vdk/vk_widget.c.s
.PHONY : vdk/vk_widget.s

# target to generate assembly for a file
vdk/vk_widget.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vdk/vk_widget.c.s
.PHONY : vdk/vk_widget.c.s

vdk/vk_window.o: vdk/vk_window.c.o
.PHONY : vdk/vk_window.o

# target to build an object file
vdk/vk_window.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vdk/vk_window.c.o
.PHONY : vdk/vk_window.c.o

vdk/vk_window.i: vdk/vk_window.c.i
.PHONY : vdk/vk_window.i

# target to preprocess a source file
vdk/vk_window.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vdk/vk_window.c.i
.PHONY : vdk/vk_window.c.i

vdk/vk_window.s: vdk/vk_window.c.s
.PHONY : vdk/vk_window.s

# target to generate assembly for a file
vdk/vk_window.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vdk/vk_window.c.s
.PHONY : vdk/vk_window.c.s

vkmio/vk_dblclick.o: vkmio/vk_dblclick.c.o
.PHONY : vkmio/vk_dblclick.o

# target to build an object file
vkmio/vk_dblclick.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vkmio/vk_dblclick.c.o
.PHONY : vkmio/vk_dblclick.c.o

vkmio/vk_dblclick.i: vkmio/vk_dblclick.c.i
.PHONY : vkmio/vk_dblclick.i

# target to preprocess a source file
vkmio/vk_dblclick.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vkmio/vk_dblclick.c.i
.PHONY : vkmio/vk_dblclick.c.i

vkmio/vk_dblclick.s: vkmio/vk_dblclick.c.s
.PHONY : vkmio/vk_dblclick.s

# target to generate assembly for a file
vkmio/vk_dblclick.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vkmio/vk_dblclick.c.s
.PHONY : vkmio/vk_dblclick.c.s

vkmio/vk_drag.o: vkmio/vk_drag.c.o
.PHONY : vkmio/vk_drag.o

# target to build an object file
vkmio/vk_drag.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vkmio/vk_drag.c.o
.PHONY : vkmio/vk_drag.c.o

vkmio/vk_drag.i: vkmio/vk_drag.c.i
.PHONY : vkmio/vk_drag.i

# target to preprocess a source file
vkmio/vk_drag.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vkmio/vk_drag.c.i
.PHONY : vkmio/vk_drag.c.i

vkmio/vk_drag.s: vkmio/vk_drag.c.s
.PHONY : vkmio/vk_drag.s

# target to generate assembly for a file
vkmio/vk_drag.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vkmio/vk_drag.c.s
.PHONY : vkmio/vk_drag.c.s

vkmio/vk_kmio.o: vkmio/vk_kmio.c.o
.PHONY : vkmio/vk_kmio.o

# target to build an object file
vkmio/vk_kmio.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vkmio/vk_kmio.c.o
.PHONY : vkmio/vk_kmio.c.o

vkmio/vk_kmio.i: vkmio/vk_kmio.c.i
.PHONY : vkmio/vk_kmio.i

# target to preprocess a source file
vkmio/vk_kmio.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vkmio/vk_kmio.c.i
.PHONY : vkmio/vk_kmio.c.i

vkmio/vk_kmio.s: vkmio/vk_kmio.c.s
.PHONY : vkmio/vk_kmio.s

# target to generate assembly for a file
vkmio/vk_kmio.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vkmio/vk_kmio.c.s
.PHONY : vkmio/vk_kmio.c.s

vkmio/vk_zone.o: vkmio/vk_zone.c.o
.PHONY : vkmio/vk_zone.o

# target to build an object file
vkmio/vk_zone.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vkmio/vk_zone.c.o
.PHONY : vkmio/vk_zone.c.o

vkmio/vk_zone.i: vkmio/vk_zone.c.i
.PHONY : vkmio/vk_zone.i

# target to preprocess a source file
vkmio/vk_zone.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vkmio/vk_zone.c.i
.PHONY : vkmio/vk_zone.c.i

vkmio/vk_zone.s: vkmio/vk_zone.c.s
.PHONY : vkmio/vk_zone.s

# target to generate assembly for a file
vkmio/vk_zone.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdk.o.dir/build.make CMakeFiles/vdk.o.dir/vkmio/vk_zone.c.s
.PHONY : vkmio/vk_zone.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... vdk-shared"
	@echo "... vdk-static"
	@echo "... vdk.o"
	@echo "... vk_demo"
	@echo "... vdk/vdk_color.o"
	@echo "... vdk/vdk_color.i"
	@echo "... vdk/vdk_color.s"
	@echo "... vdk/vk_activity.o"
	@echo "... vdk/vk_activity.i"
	@echo "... vdk/vk_activity.s"
	@echo "... vdk/vk_box.o"
	@echo "... vdk/vk_box.i"
	@echo "... vdk/vk_box.s"
	@echo "... vdk/vk_button.o"
	@echo "... vdk/vk_button.i"
	@echo "... vdk/vk_button.s"
	@echo "... vdk/vk_calendar.o"
	@echo "... vdk/vk_calendar.i"
	@echo "... vdk/vk_calendar.s"
	@echo "... vdk/vk_container.o"
	@echo "... vdk/vk_container.i"
	@echo "... vdk/vk_container.s"
	@echo "... vdk/vk_deck.o"
	@echo "... vdk/vk_deck.i"
	@echo "... vdk/vk_deck.s"
	@echo "... vdk/vk_dropdown.o"
	@echo "... vdk/vk_dropdown.i"
	@echo "... vdk/vk_dropdown.s"
	@echo "... vdk/vk_filedialog.o"
	@echo "... vdk/vk_filedialog.i"
	@echo "... vdk/vk_filedialog.s"
	@echo "... vdk/vk_filler.o"
	@echo "... vdk/vk_filler.i"
	@echo "... vdk/vk_filler.s"
	@echo "... vdk/vk_frame.o"
	@echo "... vdk/vk_frame.i"
	@echo "... vdk/vk_frame.s"
	@echo "... vdk/vk_input.o"
	@echo "... vdk/vk_input.i"
	@echo "... vdk/vk_input.s"
	@echo "... vdk/vk_label.o"
	@echo "... vdk/vk_label.i"
	@echo "... vdk/vk_label.s"
	@echo "... vdk/vk_listbox.o"
	@echo "... vdk/vk_listbox.i"
	@echo "... vdk/vk_listbox.s"
	@echo "... vdk/vk_marquee.o"
	@echo "... vdk/vk_marquee.i"
	@echo "... vdk/vk_marquee.s"
	@echo "... vdk/vk_menubar.o"
	@echo "... vdk/vk_menubar.i"
	@echo "... vdk/vk_menubar.s"
	@echo "... vdk/vk_object.o"
	@echo "... vdk/vk_object.i"
	@echo "... vdk/vk_object.s"
	@echo "... vdk/vk_popup.o"
	@echo "... vdk/vk_popup.i"
	@echo "... vdk/vk_popup.s"
	@echo "... vdk/vk_screen.o"
	@echo "... vdk/vk_screen.i"
	@echo "... vdk/vk_screen.s"
	@echo "... vdk/vk_scroller.o"
	@echo "... vdk/vk_scroller.i"
	@echo "... vdk/vk_scroller.s"
	@echo "... vdk/vk_selectbox.o"
	@echo "... vdk/vk_selectbox.i"
	@echo "... vdk/vk_selectbox.s"
	@echo "... vdk/vk_textbox.o"
	@echo "... vdk/vk_textbox.i"
	@echo "... vdk/vk_textbox.s"
	@echo "... vdk/vk_widget.o"
	@echo "... vdk/vk_widget.i"
	@echo "... vdk/vk_widget.s"
	@echo "... vdk/vk_window.o"
	@echo "... vdk/vk_window.i"
	@echo "... vdk/vk_window.s"
	@echo "... vkmio/vk_dblclick.o"
	@echo "... vkmio/vk_dblclick.i"
	@echo "... vkmio/vk_dblclick.s"
	@echo "... vkmio/vk_drag.o"
	@echo "... vkmio/vk_drag.i"
	@echo "... vkmio/vk_drag.s"
	@echo "... vkmio/vk_kmio.o"
	@echo "... vkmio/vk_kmio.i"
	@echo "... vkmio/vk_kmio.s"
	@echo "... vkmio/vk_zone.o"
	@echo "... vkmio/vk_zone.i"
	@echo "... vkmio/vk_zone.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

